### ISSUE TITLE
Is there a way to do auto-completion of file paths in `win`?

### ISSUE THREAD

**Issue by bbarker** [evbogdanov/acme#1]
If I start up `win` the run `bash`, neither tab-completion nor the mentioned `ctrl-f` in the README seem to work.

**Comment by evbogdanov** [comment]
@bbarker, in Acme, there's no such thing as tab-completion.

`ctrl-f`, however,  should work. Please try again using the absolute path: `/your/full/path`

**Comment by bbarker** [comment]
@evbogdanov awesome, that's ... interesting - but it works! thanks for the answer!
